services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - grow-ask

  grow-ask:
    build:
      context: ./backends/grow-ask
    container_name: grow-ask
    ports:
      - "4000:4000"
    env_file:
      - ./backends/grow-ask/.env
    depends_on:
      - grow-ask-db

  grow-ask-db:
    image: postgres:15
    container_name: grow-ask-db
    env_file:
      - ./backends/grow-ask/.env
    ports:
      - "5433:5432"
    volumes:
      - grow-ask-db-data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend

volumes:
  grow-ask-db-data:
